### ISSUE TITLE
user login can delete userself

### ISSUE THREAD

**Issue by iDoang** [kenhyuwa/simple-laravel-ajax#1]
why when i login and try to delete userself???
there is no permision

**Comment by kenhyuwa** [comment]
Ok, thanks for your informations

Pada tanggal 19 Nov 2016 18.17, "iDoang" notifications@github.com menulis:

why when i login and try to delete userself???
there is no permision

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
https://github.com/kenhyuwa/simple-laravel-ajax/issues/1, or mute the
thread
